# coding: utf-8

"""
    PostPuma - OpenAPI 3.0

    PostPuma API specifications

    The version of the OpenAPI document: 1.0.0
    Contact: support@postpuma.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PostPuma.models.list_media_files200_response import ListMediaFiles200Response

class TestListMediaFiles200Response(unittest.TestCase):
    """ListMediaFiles200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMediaFiles200Response:
        """Test ListMediaFiles200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListMediaFiles200Response`
        """
        model = ListMediaFiles200Response()
        if include_optional:
            return ListMediaFiles200Response(
                data = [
                    PostPuma.models.media_file.MediaFile(
                        id = '', 
                        uuid = '', 
                        name = '', 
                        mime_type = '', 
                        type = '', 
                        url = '', 
                        thumb_url = '', 
                        is_video = True, 
                        created_at = '', )
                    ]
            )
        else:
            return ListMediaFiles200Response(
        )
        """

    def testListMediaFiles200Response(self):
        """Test ListMediaFiles200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
