# coding: utf-8

"""
    PostPuma - OpenAPI 3.0

    PostPuma API specifications

    The version of the OpenAPI document: 1.0.0
    Contact: support@postpuma.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PostPuma.models.delete_media_files_request import DeleteMediaFilesRequest

class TestDeleteMediaFilesRequest(unittest.TestCase):
    """DeleteMediaFilesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteMediaFilesRequest:
        """Test DeleteMediaFilesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteMediaFilesRequest`
        """
        model = DeleteMediaFilesRequest()
        if include_optional:
            return DeleteMediaFilesRequest(
                items = [
                    56
                    ]
            )
        else:
            return DeleteMediaFilesRequest(
                items = [
                    56
                    ],
        )
        """

    def testDeleteMediaFilesRequest(self):
        """Test DeleteMediaFilesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
