# coding: utf-8

"""
    PostPuma - OpenAPI 3.0

    PostPuma API specifications

    The version of the OpenAPI document: 1.0.0
    Contact: support@postpuma.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PostPuma.models.list_accounts200_response import ListAccounts200Response

class TestListAccounts200Response(unittest.TestCase):
    """ListAccounts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAccounts200Response:
        """Test ListAccounts200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAccounts200Response`
        """
        model = ListAccounts200Response()
        if include_optional:
            return ListAccounts200Response(
                data = [
                    PostPuma.models.account.Account(
                        id = 56, 
                        uuid = '', 
                        name = '', 
                        username = '', 
                        provider = '', 
                        data = PostPuma.models.account_data.Account_data(
                            union_id = '', 
                            is_private = True, 
                            duet_disabled = True, 
                            privacy_levels = [
                                ''
                                ], 
                            stitch_disabled = True, 
                            comment_disabled = True, 
                            max_video_post_duration_sec = 56, ), 
                        authorized = True, 
                        created_at = '', )
                    ]
            )
        else:
            return ListAccounts200Response(
        )
        """

    def testListAccounts200Response(self):
        """Test ListAccounts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
