# coding: utf-8

"""
    PostPuma - OpenAPI 3.0

    PostPuma API specifications

    The version of the OpenAPI document: 1.0.0
    Contact: support@postpuma.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PostPuma.models.version_options_pinterest import VersionOptionsPinterest

class TestVersionOptionsPinterest(unittest.TestCase):
    """VersionOptionsPinterest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionOptionsPinterest:
        """Test VersionOptionsPinterest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionOptionsPinterest`
        """
        model = VersionOptionsPinterest()
        if include_optional:
            return VersionOptionsPinterest(
                title = '',
                link = '',
                boards = PostPuma.models.version_options_pinterest_boards.Version_options_pinterest_boards(
                    accounts_0 = '', )
            )
        else:
            return VersionOptionsPinterest(
        )
        """

    def testVersionOptionsPinterest(self):
        """Test VersionOptionsPinterest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
