# coding: utf-8

"""
    PostPuma - OpenAPI 3.0

    PostPuma API specifications

    The version of the OpenAPI document: 1.0.0
    Contact: support@postpuma.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PostPuma.models.version_options_tiktok import VersionOptionsTiktok

class TestVersionOptionsTiktok(unittest.TestCase):
    """VersionOptionsTiktok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionOptionsTiktok:
        """Test VersionOptionsTiktok
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionOptionsTiktok`
        """
        model = VersionOptionsTiktok()
        if include_optional:
            return VersionOptionsTiktok(
                privacy_level = PostPuma.models.version_options_tiktok_privacy_level.Version_options_tiktok_privacy_level(
                    account_0 = True, ),
                allow_comments = PostPuma.models.version_options_tiktok_privacy_level.Version_options_tiktok_privacy_level(
                    account_0 = True, ),
                allow_duet = PostPuma.models.version_options_tiktok_privacy_level.Version_options_tiktok_privacy_level(
                    account_0 = True, ),
                allow_stitch = PostPuma.models.version_options_tiktok_privacy_level.Version_options_tiktok_privacy_level(
                    account_0 = True, ),
                content_disclosure = PostPuma.models.version_options_tiktok_privacy_level.Version_options_tiktok_privacy_level(
                    account_0 = True, ),
                brand_organic_toggle = PostPuma.models.version_options_tiktok_privacy_level.Version_options_tiktok_privacy_level(
                    account_0 = True, ),
                brand_content_toggle = PostPuma.models.version_options_tiktok_privacy_level.Version_options_tiktok_privacy_level(
                    account_0 = True, )
            )
        else:
            return VersionOptionsTiktok(
        )
        """

    def testVersionOptionsTiktok(self):
        """Test VersionOptionsTiktok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
